import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://www.auvolar.com'

  return {
    rules: [
      // Allow all crawlers to access public content
      {
        userAgent: '*',
        allow: [
          '/',
          '/p/*',
          '/products',
          '/products/*',
          '/blog',
          '/blog/*',
          '/about',
          '/contact',
          '/services',
          '/shop',
          '/tools',
          '/tools/*',
          '/support',
          '/support/*',
          '/resources',
          '/resources/*',
          '/applications',
          '/applications/*',
          '/locations',
          '/locations/*',
          '/llms.txt',
          '/llms-full.txt',
        ],
        disallow: [
          '/admin',
          '/admin/*',
          '/api',
          '/api/*',
          '/login',
          '/register',
          '/cart',
          '/checkout',
          '/_next',
          '/private',
          '/portal',
          '/portal/*',
        ],
      },
      // Explicitly welcome AI crawlers — give them full public access
      {
        userAgent: [
          'GPTBot',
          'ChatGPT-User',
          'OAI-SearchBot',
          'Google-Extended',
          'Googlebot',
          'GoogleOther',
          'Claude-Web',
          'Anthropic-AI',
          'ClaudeBot',
          'PerplexityBot',
          'Bytespider',
          'CCBot',
          'cohere-ai',
          'cohere-training',
          'Meta-ExternalAgent',
          'Meta-ExternalFetcher',
          'FacebookBot',
          'YouBot',
          'Applebot-Extended',
          'Amazonbot',
          'AI2Bot',
          'Ai2Bot-Dolma',
          'iaskspider',
          'Timpibot',
          'PetalBot',
          'Diffbot',
          'ImagesiftBot',
          'omgili',
          'Webz.io',
          'PiplBot',
          'Seekr',
          'VelenpublicBot',
          'PhindBot',
        ],
        allow: [
          '/',
          '/p/*',
          '/products',
          '/products/*',
          '/blog',
          '/blog/*',
          '/about',
          '/contact',
          '/services',
          '/shop',
          '/tools',
          '/tools/*',
          '/support',
          '/support/*',
          '/resources',
          '/resources/*',
          '/applications',
          '/applications/*',
          '/locations',
          '/locations/*',
          '/case-studies',
          '/case-studies/*',
          '/partner',
          '/llms.txt',
          '/llms-full.txt',
        ],
        disallow: [
          '/admin/*',
          '/api/*',
          '/cart',
          '/checkout',
          '/portal/*',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
